##############################################################################################
#
# 3-Universal_Enrichment.R
#
# The following R script compute a Universal Enrichment analysis thorugh the package 
# ClusterProfiler using as input the tables generated by the previous script "2-RNASeq.R".
# It uses the GSEA function for gene set enrichment analysis.
#
##############################################################################################


# R packages required to run the script:
# - clusterProfiler
# - magrittr
# - tibble
# - org.Hs.eg.db

if(!require("clusterProfiler", character.only = TRUE))
{
  BiocManager::install("clusterProfiler")
  if(!require("clusterProfiler", character.only = TRUE))
  {
    stop("clusterProfiler package not found")
  }
}  

if(!require("magrittr", character.only = TRUE))
{
  install.packages("magrittr")
  if(!require("magrittr", character.only = TRUE))
  {
    stop("magrittr package not found")
  }
} 


if(!require("tibble", character.only = TRUE))
{
  install.packages("tibble")
  if(!require("tibble", character.only = TRUE))
  {
    stop("tibble package not found")
  }
} 

if(!require("org.Hs.eg.db", character.only = TRUE))
{
  BiocManager::install("org.Hs.eg.db")
  if(!require("org.Hs.eg.db", character.only = TRUE))
  {
    stop("org.Hs.eg.db package not found")
  }
}  

suppressPackageStartupMessages( c( library(clusterProfiler),
                                   library(magrittr),
                                   library(tibble),
                                   library(org.Hs.eg.db) ))

# download the data from  WikiPathways 
wpgmtfile = system.file("extdata/wikipathways-20180810-gmt-Homo_sapiens.gmt", 
                        package="clusterProfiler")
wp2gene   = read.gmt(wpgmtfile)
wp2gene   = wp2gene %>% tidyr::separate(term, c("name","version","wpid","org"), "%")
wpid2gene = wp2gene %>% dplyr::select(wpid, gene) 
wpid2name = wp2gene %>% dplyr::select(wpid, name) 

# list all the resulting tables
files = list.files("Results")

for (i in files){
  name  = gsub("\\..*","", substring(i,7) )
  GeneTable = read.csv( paste("Results/", i, sep="") )[,c(1:4)]
  
  # prepare input for GSEA function
  geneList = data.frame(GeneTable$ENTREZID, 2^GeneTable$logFC)
  
  geneList = na.omit(geneList)
  geneList = geneList[!duplicated(geneList$GeneTable.ENTREZID),]
  geneList <- sort(deframe(geneList), decreasing = T)
  
  
  # computing gene set enrichment analysis
  ewp <- GSEA(geneList, TERM2GENE = wpid2gene, TERM2NAME = wpid2name, verbose=FALSE,
              pvalueCutoff = 1, scoreType="pos") 
  # convert the gene IDs to gene symbols
  ewpSymbol <- setReadable(ewp, org.Hs.eg.db, keyType = "ENTREZID")
  
  write.table(ewpSymbol@result, 
            paste("UEA/", name ,".txt",sep=""), quote=F, row.names = F,sep=";")
}
